name: Automatically Assign Issues

on:
  issues:
    types:
      - opened

jobs:
  main:
    runs-on: ubuntu-latest
  
    steps:
      - name: Assign Issue

        uses: KentuckyDev/assign-issue@v1

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "caidensanders-wsu"
