name: Automatically Assign Issues

on:
  issues:
    types:
      - opened

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      issues: write
  
    steps:
      - name: Assign Issue

        uses: pozil/auto-assign-issue@v2

        with:
          assignees: "caidensanders-wsu"
          numOfAssignee: 1
